import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/providers";
import AnimatedBackground from "@/ui/components/AnimatedBackground";

const cairo = Cairo({
  weight: ["400", "500", "600", "700", "800", "900", "1000", "300", "200"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.className} antialiased`}>
        <Providers>
          <div className="relative flex min-h-screen w-full flex-col items-center">
            <AnimatedBackground />
            <div className="relative z-10 flex w-full max-w-7xl flex-1 flex-col px-4 sm:px-6 lg:px-8">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
